x = float(input("Enter initial value for x: "))
print(x)
x += float(input("Enter value to add: "))
print(x)
x -= float(input("Enter value to subtract: "))
print(x)
x *= float(input("Enter value to multiply: "))
print(x)
x /= float(input("Enter value to divide: "))
print(x)
x %= float(input("Enter value to take modulus: "))
print(x)
x //= float(input("Enter value to take floor division: "))
